apiVersion: apps/v1
kind: Deployment
metadata:
  name: lights-ewp1 # East West Pedestrian 1
  labels:
    app: lights-ewp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-ewp1
  template:
    metadata:
      labels:
        app: lights-ewp1
    spec:
      containers:
      - name: lights-ewp1
        image: softsecgroup6/lights
        ports:
        - containerPort: 8080
        env:
          - name: ID
            value: "EWP1"
