apiVersion: apps/v1
kind: Deployment
metadata:
  name: lights-ewp2 # East West Pedestrian 2
  labels:
    app: lights-ewp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-ewp2
  template:
    metadata:
      labels:
        app: lights-ewp2
    spec:
      containers:
      - name: lights-ewp2
        image: softsecgroup6/lights
        ports:
        - containerPort: 8080
        env:
          - name: ID
            value: "EWP2"
