apiVersion: apps/v1
kind: Deployment
metadata:
  name: lights-nsc1 # North South Car 1
  labels:
    app: lights-nsc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-nsc1
  template:
    metadata:
      labels:
        app: lights-nsc1
    spec:
      containers:
      - name: lights-nsc1
        image: softsecgroup6/lights
        ports:
        - containerPort: 8080
        env:
          - name: ID
            value: "NSC1"
