apiVersion: apps/v1
kind: Deployment
metadata:
  name: lights-nsp1 # North South Ped 1
  labels:
    app: lights-nsp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-nsp1
  template:
    metadata:
      labels:
        app: lights-nsp1
    spec:
      containers:
      - name: lights-nsp1
        image: softsecgroup6/lights
        ports:
        - containerPort: 8080
        env:
          - name: ID
            value: "NSP1"
