apiVersion: apps/v1
kind: Deployment
metadata:
  name: lights-nsp2 # North South Ped 2
  labels:
    app: lights-nsp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-nsp2
  template:
    metadata:
      labels:
        app: lights-nsp2
    spec:
      containers:
      - name: lights-nsp2
        image: softsecgroup6/lights
        ports:
        - containerPort: 8080
        env:
          - name: ID
            value: "NSP2"
