apiVersion: apps/v1
kind: Deployment
metadata:
  name: lights-snc1 # South North Car 1
  labels:
    app: lights-snc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-snc1
  template:
    metadata:
      labels:
        app: lights-snc1
    spec:
      containers:
      - name: lights-snc1
        image: softsecgroup6/lights
        ports:
        - containerPort: 8080
        env:
          - name: ID
            value: "SNC1"
