apiVersion: apps/v1
kind: Deployment
metadata:
  name: lights-snp1 # South North Ped 1
  labels:
    app: lights-snp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-snp1
  template:
    metadata:
      labels:
        app: lights-snp1
    spec:
      containers:
      - name: lights-snp1
        image: softsecgroup6/lights
        ports:
        - containerPort: 8080
        env:
          - name: ID
            value: "SNP1"
