apiVersion: apps/v1
kind: Deployment
metadata:
  name: lights-snp2 # South North Ped 2
  labels:
    app: lights-snp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-snp2
  template:
    metadata:
      labels:
        app: lights-snp2
    spec:
      containers:
      - name: lights-snp2
        image: softsecgroup6/lights
        ports:
        - containerPort: 8080
        env:
          - name: ID
            value: "SNP2"
