apiVersion: apps/v1
kind: Deployment
metadata:
  name: lights-wec1 # West East Car 1
  labels:
    app: lights-wec1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-wec1
  template:
    metadata:
      labels:
        app: lights-wec1
    spec:
      containers:
      - name: lights-wec1
        image: softsecgroup6/lights
        ports:
        - containerPort: 8080
        env:
          - name: ID
            value: "WEC1"
