apiVersion: apps/v1
kind: Deployment
metadata:
  name: lights-wec2 # West East Car 2
  labels:
    app: lights-wec2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lights-wec2
  template:
    metadata:
      labels:
        app: lights-wec2
    spec:
      containers:
      - name: lights-wec2
        image: softsecgroup6/lights
        ports:
        - containerPort: 8080
        env:
          - name: ID
            value: "WEC2"
